def is_supported_file(filename):
    return (
        filename.endswith(".ts")
        or filename.endswith(".js")
        or filename.endswith(".tsx")
        or filename.endswith(".sh")
        or filename.endswith(".py")
        or filename.endswith(".md")
        or filename.endswith(".json")
        or filename.endswith(".yml")
        or filename.endswith(".yaml")
        or filename.endswith(".html")
        or filename.endswith(".css")
        or filename.endswith(".scss")
        or filename.endswith(".less")
        or filename.endswith(".xml")
        or filename.endswith(".java")
        or filename.endswith(".cs")
        or filename.endswith(".cpp")
        or filename.endswith(".c")
        or filename.endswith(".h")
        or filename.endswith(".go")
        or filename.endswith(".php")
        or filename.endswith(".rb")
        or filename.endswith(".swift")
        or filename.endswith(".kt")
        or filename.endswith(".dart")
        or filename.endswith(".sql")
        or filename.endswith(".graphql")
        or filename.endswith(".gql")
        or filename.endswith(".txt")
    ) and not (
        filename.endswith(".min.js")
        or filename.endswith(".min.css")
        or filename.endswith("pnpm-lock.yaml")
        or filename.endswith("result.json")
    )
